services:
  bank:
      container_name: bank_api
      image: bank:1.0.0
      build:
        context: .
        dockerfile: go.dockerfile
      environment:
        DATABASE_URL: 'host=localhost user=postgres password=postgres dbname=gobank port=5432 sslmode=disable'
      ports:
        - '8080:8080'
      depends_on:
        - db
  db:
    container_name: bank_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobank  
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}